FROM python:3.11-slim

WORKDIR /usr/src/app

# Install dependencies
COPY ./api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# El código de la API se montará como un volumen,
# por lo que no necesitamos copiarlo aquí para desarrollo.

# Comando para iniciar el servidor de desarrollo de FastAPI
# --host 0.0.0.0 permite que sea accesible desde fuera del contenedor
# --reload reinicia el servidor al detectar cambios en el código
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]