# docker-compose.yaml
services:
  postgres_db:
    container_name: postgres_db
    build:
      context: . # El contexto es la raíz del proyecto
      dockerfile: ./docker/postgres/Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  scraper:
    container_name: scraper
    build:
      context: .
      dockerfile: ./docker/scraper/Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./scraper:/usr/src/app # Montamos el código del scraper para desarrollo
      - ./database:/usr/src/app/database # Montamos la carpeta database para Alembic
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: