"""Initial database schema

Revision ID: 54e4ceb42a33
Revises: 
Create Date: 2025-09-03 18:08:36.818794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e4ceb42a33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_name_parent_id_key'), 'categories', type_='unique')
    op.create_unique_constraint('_category_parent_uc', 'categories', ['name', 'parent_id'])
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_unique_constraint(None, 'categories', ['name'])
    op.alter_column('manufacturers', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_manufacturers_id'), 'manufacturers', ['id'], unique=False)
    op.alter_column('products', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'product_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'base_price_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('products_product_url_key'), 'products', type_='unique')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_product_url'), 'products', ['product_url'], unique=True)
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_index(op.f('ix_products_product_url'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_unique_constraint(op.f('products_product_url_key'), 'products', ['product_url'], postgresql_nulls_not_distinct=False)
    op.alter_column('products', 'base_price_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'product_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_manufacturers_id'), table_name='manufacturers')
    op.alter_column('manufacturers', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_constraint('_category_parent_uc', 'categories', type_='unique')
    op.create_unique_constraint(op.f('categories_name_parent_id_key'), 'categories', ['name', 'parent_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
