"""Test after cleanup

Revision ID: 20c97941f03f
Revises: 54e4ceb42a33
Create Date: 2025-09-07 15:40:47.569616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c97941f03f'
down_revision = '54e4ceb42a33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
