"""Update product schema to match models

Revision ID: 38b2e008c07a
Revises: 20c97941f03f
Create Date: 2025-09-10 18:29:22.330781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b2e008c07a'
down_revision = '20c97941f03f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.add_column('products', sa.Column('base_price_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('base_price_unit', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('base_price_quantity', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('details', sa.JSON(), nullable=True))
    op.drop_column('products', 'description')
    op.drop_column('products', 'base_price_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('base_price_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'details')
    op.drop_column('products', 'base_price_quantity')
    op.drop_column('products', 'base_price_unit')
    op.drop_column('products', 'base_price_amount')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
