# docker/scraper/Dockerfile.dev
FROM python:3.11-slim

WORKDIR /usr/src/app

COPY ./scraper/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el script de entrada que mantiene el contenedor vivo
COPY ./scraper/main.py .

CMD ["python", "main.py"]