# docker/scraper/Dockerfile.prod
FROM python:3.11-slim

WORKDIR /usr/src/app

# Copiamos solo los requisitos primero para aprovechar el cache de Docker
COPY ./src/scraper/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Ahora copiamos todo el proyecto del scraper
COPY ./src/scraper/ .

# El comando por defecto en producción sería ejecutar el scraper directamente
# o a través de un programador de tareas.
CMD ["scrapy", "crawl", "edeka"]